Team-DogWalk/DogWalk

DogWalk.xcodeproj/project.pbxproj, DogWalk/Presentatiton/Components/Common/CommonButton.swift, DogWalk/Presentatiton/Components/Common/CommonProfile.swift
<br />
Common 프로필, 버튼 구현
<br />
<br /><br />
<br />
<br />
Common 버튼 사용 시 왼쪽, 오른쪽 이미지 추가는 옵션입니다.
왼쪽 이미지, 오른쪽 이미지 둘다 디폴트 nil로 선언되어 있습니다. 
이미지 넣을 시 이미지 size는 디폴트 값으로 30이므로 다른 사이즈로 변경 시 변수 imageSize를 통해 조절 해 주세요~
=> UI: Common 프로필, 버튼 구현

DogWalk/Presentatiton/Screens/Community/CommunityView.swift, DogWalk/Presentatiton/Screens/Community/Detail/CommunityDetailView.swift, DogWalk/Presentatiton/Utils/Extension/Image+.swift
<br />
- 커뮤니티 게시물 상세화면 UI 구현 (제목/내용/댓글 리스트/댓글 작성뷰)
<br />
<br /><br />
closed #5 
<br />
- View 코드 분리된거나 데이터 들어가야되는 부분 주석 이해 안되시면 알려주세요
<br />
- SF Symbol 사용하는 곳에 이미지가 안 나와서 확인해보니 systemName이 빠져있어서 해당 부분 수정했습니당!
=> UI: CcommunityDetailView 구현

DogWalk.xcodeproj/project.pbxproj, DogWalk/Presentatiton/Screens/Chatting/ChattingView.swift
- [] 기능 작업
<br />
- 채팅 리스트 화면 UI 구현
<br />
<br /><br />
=> UI: ChattingListView 구현

DogWalk/Presentatiton/Screens/Chatting/ChattingView.swift, DogWalk/Presentatiton/Screens/Community/CommunityView.swift
<br />
- 게시물 리스트 화면 구현 
- 채팅 리스트 뷰 충돌 해결
<br />
<br /><br />
- closed #16
<br />
- 정섭님 경고 1회요 😇
=> UI: 게시물 리스트 화면 구현 + 채팅 리스트 뷰 충돌 해결

DogWalk.xcodeproj/project.pbxproj, DogWalk/Presentatiton/Screens/Community/CommunityView.swift, DogWalk/Presentatiton/Screens/Community/Create/CommunityCategorySelectedView.swift, DogWalk/Presentatiton/Screens/Community/Create/CommunityCreateView.swift
<br />
- 커뮤니티 게시물 작성 뷰 구현
- 카테고리 선택 시 BottomSheet 
<br />
<br /><br />
closed #13
=> UI: 커뮤니티 게시물 작성 화면 UI 구성

DogWalk/Info.plist, DogWalk/Presentatiton/Components/Common/CommonSendView.swift
<br />
사용자 갤러리 불러오기 구현
<br />
<br /><br />
<br />
파일 구조를 어떤식으로 쪼갤지 고민중입니다...
<br />
https://www.youtube.com/watch?v=qlmequ3a0Og&t=1252s
참고 자료가 오래된 레퍼런스여서 최신버전으로 리팩토링 진행해야될거 같습니다.
현재 문제점으로 과도한 메모리 사용, 사용자 갤러리 접근 시 전체 사진 접근으로 인해 렉 발생 합니다.
이미지 캐싱 구현 시 주석 부분에 캐싱 적용해서 캐싱 전략도 하면 좋을거같아요~
추가적으로 AV도 함께 불러올지 논의해봐야될거 같아요~
https://inuplace.tistory.com/1238
https://blog.stackademic.com/swiftui-photos-app-copy-cat-and-deep-dive-into-photokit-part-1-fetch-assets-and-display-68de56391481
이미지 불러오기 개선하기 위한 참고 레퍼런스
=> UI: Chatting 이미지 뷰, 로직 구현

DogWalk/Presentatiton/Components/Common/CommonSendView.swift, DogWalk/Presentatiton/Screens/Chatting/ChattingRoomView.swift, DogWalk/Presentatiton/Screens/Chatting/MessageModel.swift
<br />
- 사진을 올리기 위한 버튼 UI 리팩토링
- 상위뷰에서 사용자가 클릭한 이미지 전달을 위한 completionSendImage: ((UIImage) -> ())?  구현
- 채팅창 이미지 보낼 경우의 채팅 말풍선 뷰 구현
- 영상 미사용으로 인해 관련 코드 주석처리
- 이미지 선택에 대한 예외처리 진행
<br />
<br /><br />
<br />
<br />
=> Feat: 채팅 사진 업로드 기능 구현

DogWalk/Presentatiton/Screens/Chatting/ChattingRoomView.swift, DogWalk/Presentatiton/Screens/Chatting/MessageModel.swift
<br />
채팅방 상대방일 경우 이미지 말풍선 레이아웃 조절
상대방 프로필 레이아웃 조절
if문에서 switch문으로 분기처리 진행
<br />
<br /><br />
<br />
<br />
=> Fix: ChatView 이미지 셀 레이아웃 수정

DogWalk.xcodeproj/project.pbxproj, DogWalk/Application/ContentView.swift, DogWalk/DogWalk.entitlements, DogWalk/Presentatiton/Screens/Auth/AuthView.swift
<br />
- 기존 커스텀 버튼에서 애플에서 제공하는 기본 버튼으로 변경
- 애플 로그인 구현 
- 로그인 화면 미사용 카카오 로그인 주석처리 진행
<br />
<br /><br />
<br />
DB연결 시 로그인 결과 연결할 예정
<br />
=> Feat: Apple Login 구현

DogWalk.xcodeproj/project.pbxproj, DogWalk/Data/Repositories/Local/User/UserDefaults.swift, DogWalk/Data/Repositories/Local/User/UserManager.swift
<br />
UserdefaultsManager 구현
- UserDefaults 저장값
- 토큰
- 리프레시 토큰 (만료시 로그인 화면에서 재로그인 유도)
- 유저 정보
- 닉네임
- 주소(x,y)
- 도로명 주소
- 포인트 (Int)
- 총 산책시간(초단위 Int)
- 게시물 작성 횟수 (Int)
- 성별
<br />
closed #48 
<br />
<br />
- 추가로 필요한 데이터가 있다면 말씀해주세요~
=> Feat: UserdefaultsManager 구현

DogWalk.xcodeproj/project.pbxproj, DogWalk/Application/ContentView.swift, DogWalk/Application/Coordinator/CoordinatorImpl.swift, DogWalk/Application/Coordinator/CoordinatorView.swift, DogWalk/Application/Coordinator/DogWalkCoordinatorProtocol.swift, DogWalk/Application/Coordinator/MainCoordinator.swift, DogWalk/Presentatiton/Screens/Chatting/ChattingView.swift, DogWalk/Presentatiton/Screens/Community/CommunityView.swift
<br />
- Coordinator 패턴 도입으로 화면 전환 로직 중앙 관리
<br />
closed #55 
<br />
- 궁금하신 부분이나 이해가 안되시는 부분 있으면 편하게 말씀해주세요!
<br />
- ChattingView -> ChattingRoomView 화면 이동에 간단하게 적용시켜놨습니다!
=> Feat: Coordinator 구현

DogWalk/Data/DTOs/Remote/Auth/AuthDTO.swift, DogWalk/Data/Network/AuthTarget.swift, DogWalk/Data/Network/ChatTarget.swift, DogWalk/Data/Network/NetworkError.swift, DogWalk/Data/Network/NetworkManager.swift, DogWalk/Data/Network/PostTarget.swift, DogWalk/Data/Network/TargetType.swift, DogWalk/Data/Network/UserTarget.swift, DogWalk/Data/Repositories/Local/User/UserDefaults.swift, DogWalk/Data/Repositories/Local/User/UserManager.swift
<br />
- AccessToken, RefreshToken 갱신
- 토큰 갱신 후 기존 진행 중이던 네트워크 재진행
- 토큰 이외 네트워크 오류 예외 발생 시 재시도 처리 (조금 더 손봐야해요!)
<br />
- 기존 네트워크 호출 플로우
- 토큰 갱신 후 기존 네트워크 재호출 플로우
<br /><br />
closed #53 
<br />
- RetryHandler 부분이랑, 사용하는 부분 한 번 봐주세요 ㅠㅠ
- RetryHandler를 별도 파일로 분리해두어야 할지 고민입니다~! 의견 부탁드려요
<br />
- ### 늦어서 죄송해요 삐질..😵‍💫
=> Feat: Access/RefreahToken 갱신 처리, 기존 네트워크 재호출 처리

DogWalk.xcodeproj/project.pbxproj
<br />
- WalkResultView 재생성성
<br />
closed #54 
<br />
=> Chore: WalkResultView conflict해결

DogWalk.xcodeproj/project.pbxproj, DogWalk/Data/DTOs/Remote/User/OAuthLoginDTO.swift, DogWalk/Data/Network/NetworkManager.swift
<br />
- RetryHandler 실행 로직 수정
<br />
- 네트워크 재시도 플로우
- 토큰 갱신 처리 중 재시도 플로우
<br /><br />
closed #53 
<br />
- RetryHandler 별도 파일로 구성할까요?
<br />
- 확인 해주신 성민님 감사합니다 ~~~~ !!!
- 사용하시다가 로직 이해 안 되시는 부분 있으면 말씀해주세용
=> Fix: RetryHandler 실행 로직 수정

DogWalk.xcodeproj/project.pbxproj, DogWalk/Info.plist, DogWalk/Presentatiton/Screens/Map/LocationManager.swift, DogWalk/Presentatiton/Screens/Map/MapView.swift
<br />
- 사용자가 이동한 경로 보여줌
<br />
<br /><br />
cloded #47
=> Feat: MapView에서 사용자가 이동한 path를 보여줌

DogWalk.xcodeproj/project.pbxproj, DogWalk/Application/DogWalkApp.swift, DogWalk/Data/CoreData/Chat.xcdatamodeld/Chat.xcdatamodel/contents, DogWalk/Data/CoreData/ChatMessage+CoreDataClass.swift, DogWalk/Data/CoreData/ChatMessage+CoreDataProperties.swift, DogWalk/Data/CoreData/ChatRoom+CoreDataClass.swift, DogWalk/Data/CoreData/ChatRoom+CoreDataProperties.swift, DogWalk/Data/CoreData/Repository/ChatRepository.swift, DogWalk/Data/CoreData/Repository/CoreDataManager.swift, DogWalk/Data/DTOs/Remote/User/MyProfileDTO.swift, DogWalk/Data/Repositories/Local/CoreData/Chat.xcdatamodeld/Chat.xcdatamodel/contents, DogWalk/Data/Repositories/Local/CoreData/ChatMessageRepository.swift, DogWalk/Data/Repositories/Local/CoreData/ChatRoomRepository.swift, DogWalk/Data/Repositories/Local/CoreData/DogProfile.xcdatamodeld/DogProfile.xcdatamodel/contents, DogWalk/Data/Repositories/Local/User/UserDefaults.swift, DogWalk/Data/Repositories/Local/User/UserManager.swift, DogWalk/Presentatiton/Screens/Chatting/ChattingTestView.swift, DogWalk/Presentatiton/Screens/Home/HomeView.swift, DogWalk/Presentatiton/Screens/Map/CommunityView.swift
<br />
- CoreData Repository CRUD 기능 구현
<br />
<br /><br />
closed #31 
<br />
<br />
- Presentatiton -> Chatting -> TestView 하나 있습니다!
=> Feat: CoreData Repository 구현

DogWalk.xcodeproj/project.pbxproj
<br />
- 수정 전) path = /Users/yoonwoo/Desktop/sessac/SLP/DogWalk/Data/CoreData/Chat.xcdatamodeld;
- 수정 후) path = Chat.xcdatamodeld;
<br />
closed #73
<br />
=> Fix: Fixed CoreData path

DogWalk.xcodeproj/project.pbxproj, DogWalk/Application/Coordinator/CoordinatorView.swift, DogWalk/Domain/UserCases/CommunityUseCase.swift, DogWalk/Presentatiton/Screens/Community/MainCommunity/CommunityIntent.swift, DogWalk/Presentatiton/Screens/Community/MainCommunity/CommunityView.swift, DogWalk/Presentatiton/Screens/Home/HomeView.swift, DogWalk/Presentatiton/Screens/Map/CommunityView.swift
<br />
community UseCase 프로토콜 구현
<br />
<br /><br />
<br />
<br />
UseCase관련 궁금한 점 있으시면 카톡주세요~
=> Refactor: CommunityView UseCase 구현

DogWalk/Data/Network/NetworkManager.swift
<br />
<br />
<br /><br />
closed #88 
<br />
<br />
=> Refactor: 네트워크 Request 함수 DTO 반환 타입 추가

DogWalk.xcodeproj/project.pbxproj, DogWalk/Application/Coordinator/MainCoordinator.swift, DogWalk/Data/DTOs/Remote/Post/LikePostDTO.swift, DogWalk/Data/DTOs/Remote/Post/PostDTO.swift, DogWalk/Data/DTOs/Remote/Post/PostResponseDTO.swift, DogWalk/Data/DTOs/Remote/Post/Request/CommentBody.swift, DogWalk/Data/DTOs/Remote/Post/Request/GetGeoLocationQuery.swift, DogWalk/Data/Network/NetworkManager.swift, DogWalk/Data/Network/PostTarget.swift, DogWalk/Data/Repositories/Local/Image/ImageCacheManager.swift, DogWalk/Domain/UserCases/CommunityDetailUseCase.swift, DogWalk/Domain/UserCases/CommunityUseCase.swift, DogWalk/Presentatiton/Components/Base/ContentState.swift, DogWalk/Presentatiton/Components/Common/CommonErrorView.swift, DogWalk/Presentatiton/Components/Common/CommonLoadingView.swift, DogWalk/Presentatiton/Components/Common/CommonProfile.swift, DogWalk/Presentatiton/Screens/Chatting/ChattingList/ChattingListView.swift, DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomView.swift, DogWalk/Presentatiton/Screens/Community/Detail/CommunityDetailIntent.swift, DogWalk/Presentatiton/Screens/Community/Detail/CommunityDetailState.swift, DogWalk/Presentatiton/Screens/Community/Detail/CommunityDetailView.swift, DogWalk/Presentatiton/Screens/Community/MainCommunity/CommunityState.swift, DogWalk/Presentatiton/Screens/Community/MainCommunity/CommunityView.swift, DogWalk/Presentatiton/Screens/Home/HomeView.swift, DogWalk/Presentatiton/Screens/Map/MapOverview/MapView.swift, DogWalk/Presentatiton/Screens/Map/WalkResult/WalkResultView.swift, DogWalk/Presentatiton/Utils/Extension/Image+.swift
<br />
- community detail MVI 구조화
- community detail UseCase 구현
- 댓글 작성 네트워크 구현
- 기존 CommonProfile 리팩토링 -> 이미지 대신 url값을 받습니다.
- CommonErrorView, CommonLoadingView 파일 생성
- communityView 사소한 수정 진행
<br />
<br /><br />
closed #84
=> Refactor: CommunityDetailView MVI 적용

DogWalk/Data/Repositories/Local/Image/ImageCacheManager.swift, DogWalk/Data/Repositories/Local/User/UserDefaults.swift, DogWalk/Data/Repositories/Local/User/UserManager.swift, DogWalk/Presentatiton/Screens/Home/HomeState.swift
<br />
-  이미지 캐싱 리팩토링
- 이미지 캐싱 etag 적용
- 이미지 캐싱 로직 중 document에 저장되는 로직 구현
<br />
<br /><br />
<br />
<br />
=> Feat/93 etag 구현

DogWalk/Presentatiton/Screens/Home/HomeState.swift
<br />
- HomeState 수정
<br />
<br /><br />
<br />
<br />
=> Fix: HomeState 수정

DogWalk.xcodeproj/xcshareddata/xcschemes/DogWalk.xcscheme, DogWalk/Info.plist, DogWalk/Presentatiton/Screens/Map/MapOverview/MapIntent.swift, DogWalk/Presentatiton/Screens/Map/MapOverview/MapState.swift, DogWalk/Presentatiton/Screens/Map/MapOverview/MapView.swift
<br />
- BackgroundMode에서 DispatchSourceTimer로 타이머 구현 변경
<br />
<br /><br />
closed #90
<br />
=> Refactor: BackgroundMode에서 DispatchSourceTimer로 타이머 구현 변경

DogWalk.xcodeproj/project.pbxproj, DogWalk/Data/CoreData/Repository/ChatRepository.swift, DogWalk/Data/Network/NetworkManager.swift, DogWalk/Data/Repositories/Local/Image/ImageCacheManager.swift, DogWalk/Presentatiton/Screens/Community/Detail/CommunityDetailView.swift, DogWalk/Presentatiton/Screens/Home/HomeIntent.swift
<br />
New 채팅방 만들기 구현
<br />
<br /><br />
<br />
<br />
=> Feat: New 채팅방 만들기 구현

DogWalk/Data/CoreData/Repository/ChatRepository.swift
<br />
- 멍톡 탭 진입 시 DB의 마지막 채팅 내용과 비교하여 최신 메세지 업데이트
<br />
<br /><br />
<br />
<br />
=> Feat: 멍톡 탭 진입 시 DB에 최신 채팅 메세지 업데이트 반영

DogWalk.xcodeproj/project.pbxproj, DogWalk/Presentatiton/Screens/Map/MapOverview/MapIntent.swift, DogWalk/Presentatiton/Screens/Map/MapOverview/MapState.swift, DogWalk/Presentatiton/Screens/Map/MapOverview/MapView.swift
<br />
Map 로직 및 뷰 연결
<br />
<br /><br />
<br />
<br />
=> Feat: MapView 로직 연결

DogWalk.xcodeproj/project.pbxproj, DogWalk/Data/CoreData/Repository/ChatRepository.swift, DogWalk/Data/Network/NetworkError.swift, DogWalk/Data/Network/Socket/SocketIOManager.swift, DogWalk/Domain/UseCases/Chatting/ChattingListUseCase.swift, DogWalk/Domain/UseCases/Chatting/ChattingRoomUseCase.swift, DogWalk/Presentatiton/Screens/Chatting/ChattingList/ChattingListIntent.swift, DogWalk/Presentatiton/Screens/Chatting/ChattingList/ChattingListView.swift, DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomIntent.swift, DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomState.swift
<br />
<br />
<br /><br />
<br />
<br />
=> Feat: 채팅 전송 기능 구현 및 화면 연동

DogWalk.xcodeproj/project.pbxproj, DogWalk/Data/DTOs/Remote/Auth/AuthDTO.swift, DogWalk/Data/Network/AuthTarget.swift, DogWalk/Data/Network/NetworkManager.swift, DogWalk/Data/Repositories/Local/Image/ImageCacheManager.swift, DogWalk/Domain/UseCases/CommunityDetailUseCase.swift, DogWalk/Presentatiton/Screens/Community/Detail/CommunityDetailView.swift, DogWalk/Presentatiton/Screens/Community/MainCommunity/CommunityView.swift, DogWalk/Presentatiton/Screens/Login/LoginState.swift, DogWalk/Presentatiton/Screens/Login/LoginView.swift
<br />
- 리패래쉬 토큰 및 requestDTO 리팩토링 진행
- request Future 버전 삭제
<br />
<br /><br />
<br />
<br />
baseHeader에 이메일, 비밀번호 입력해서 사용합시당.
같은 계정으로 로그인 시 리프래쉬 토큰 이슈 문제 발생!
=> Refactor: 리프레쉬 토큰

DogWalk/Data/DTOs/Remote/Post/PostDTO.swift, DogWalk/Data/Network/NetworkManager.swift, DogWalk/Presentatiton/Screens/Community/MainCommunity/CommunityView.swift
<br />
- 페이지네이션 구현
<br />
<br /><br />
<br />
<br />
=> Feat: CommunityView 페이지네이션 구현

DogWalk/Data/Network/NetworkManager.swift, DogWalk/Data/Repositories/Local/User/UserManager.swift, DogWalk/Presentatiton/Screens/Home/HomeView.swift, DogWalk/Presentatiton/Screens/Map/MapOverview/MapIntent.swift, DogWalk/Presentatiton/Screens/Map/MapOverview/MapState.swift, DogWalk/Presentatiton/Screens/Map/MapOverview/MapView.swift
<br />
- 새로고침 시 Annotation 안 나오는 오류 해결
- 위치 기반 기능에서 산책 인증만 나와야 하는데, 다른 게시물도 같이 나오는 오류 해결
- 현위치 버튼 구현 완료
<br />
<br /><br />
closed #131
<br />
=> Fix: Modifiying MapView Logic

DogWalk/Application/Coordinator/CoordinatorView.swift, DogWalk/Application/Coordinator/DogWalkCoordinatorProtocol.swift, DogWalk/Application/Coordinator/MainCoordinator.swift, DogWalk/Data/Network/NetworkManager.swift, DogWalk/Presentatiton/Screens/Auth/AuthView.swift
<br />
- 애플 로그인 구현
- 코디네이터 start 구현
- start에 로그인 유무에 따라 뷰 tab or 로그인 으로 변경
<br />
<br /><br />
<br />
<br />
=> 애플 loginview 구현

DogWalk.xcodeproj/project.pbxproj, DogWalk/Application/DogWalkApp.swift, DogWalk/Data/CoreData/CustomType/CoreChatMessage.swift, DogWalk/Data/Network/NetworkError.swift, DogWalk/Data/Network/Socket/SocketIOManager.swift, DogWalk/Data/Repositories/Local/User/UserDefaults.swift, DogWalk/Data/Repositories/Local/User/UserManager.swift, DogWalk/DogWalk/Data/CoreData/CoreChatRoom.xcdatamodeld/CoreChatRoom.xcdatamodel/contents, DogWalk/Domain/UseCases/Chatting/ChattingRoomUseCase.swift, DogWalk/Info.plist, DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomIntent.swift, DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomView.swift, DogWalk/Presentatiton/Screens/Home/HomeView.swift, DogWalk/Presentatiton/Screens/Login/LoginView.swift
<br />
- AppDelegate 내에서 Background Task 구현
- ChattingRoomView scenePhase 변경 시 Background Task 실행
<br />
<br /><br />
closed #130 
<br />
- Background Task는 실기기 빌드해서 테스트 해봐야 하는데 제 기기에서 자꾸 오류나서, 정섭님 기기로 빌드 후 테스트 해보겠습니다 !!
=> Feat: Socket Background Task

DogWalk/Data/CoreData/Repository/ChatRepository.swift, DogWalk/Presentatiton/Components/Common/CommonSendView.swift, DogWalk/Presentatiton/Screens/Community/Detail/CommunityDetailView.swift
<br />
- 새로운 채팅 유저와 채팅시 오류 수정
- 게시물 -> 채팅 -> 게시물 이동 중 키보드 런타임 오류 수정
<br />
<br /><br />
closed #150 
<br />
=> Fix:  새로운 채팅 유저와 채팅시 오류 해결

DogWalk.xcodeproj/project.pbxproj, DogWalk/Presentatiton/Screens/Community/Create/CommunityCreateView.swift, DogWalk/Presentatiton/Screens/Map/WalkResultCreate/WalkResultCreateView.swift, DogWalk/Presentatiton/Screens/Setting/SettingView.swift
<br />
- 포스트 게시 완료 또는 에러 시 얼럿 피드백 구현
<br />
<br /><br />
<br />
<br />
=> 게시글 작성뷰 얼럿 구현

DogWalk.xcodeproj/project.pbxproj, DogWalk/Data/CoreData/Repository/ChatRepository.swift, DogWalk/Data/DTOs/Remote/Chat/LastChatDTO.swift, DogWalk/Domain/UseCases/Chatting/ChattingRoomUseCase.swift, DogWalk/Presentatiton/Components/Common/CommonImageView.swift, DogWalk/Presentatiton/Screens/Chatting/ChattingList/ChattingListView.swift, DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomIntent.swift, DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomView.swift
<br />
- 채팅 이미지 전송 API 연결
- 채팅 이미지 CoreData 저장
<br />
<br /><br />
<br />
<br />
=> Feat: 채팅 이미지 전송 기능 구현

DogWalk/Data/Repositories/Local/Image/ImageCacheManager.swift, DogWalk/Domain/UseCases/CommunityUseCase.swift, DogWalk/Presentatiton/Screens/Chatting/ChattingList/ChattingListIntent.swift, DogWalk/Presentatiton/Screens/Chatting/ChattingList/ChattingListState.swift, DogWalk/Presentatiton/Screens/Chatting/ChattingList/ChattingListView.swift, DogWalk/Presentatiton/Screens/Community/Detail/CommunityDetailView.swift, DogWalk/Presentatiton/Screens/Community/MainCommunity/CommunityIntent.swift, DogWalk/Presentatiton/Screens/Community/MainCommunity/CommunityView.swift, DogWalk/Presentatiton/Screens/Map/MapOverview/MapView.swift
<br />
- 채팅룸 서치 구현 및 포스터 뷰 리팩토링 진행
<br />
<br /><br />
<br />
<br />
=> Refactor: 채팅룸 서치 구현 및 포스터 뷰 리팩토링 진행

DogWalk/Application/Coordinator/DogWalkCoordinatorProtocol.swift, DogWalk/Application/Coordinator/MainCoordinator.swift, DogWalk/Presentatiton/Components/Common/CommonImageView.swift, DogWalk/Presentatiton/Screens/Chatting/ChattingList/ChattingListView.swift, DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomIntent.swift, DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomState.swift, DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomView.swift, DogWalk/Presentatiton/Screens/Community/Detail/CommunityDetailView.swift, DogWalk/Presentatiton/Screens/Map/MapOverview/MapView.swift
<br />
- 상대방 닉네임으로 채팅방 NavigationTitle 수정
- 이미지 셀 contentMode 수정
<br />
<br /><br />
closed #161 
<br />
<br />
- cursorDate, coredata 다시 확인이 필요한 거 같아요....ㅠ...
=> UI: 채팅방 입장 시  NavigationTitle 상대방 닉네임 처리, 이미지 셀 contentMode 수정

DogWalk.xcodeproj/project.pbxproj, DogWalk/Data/DTOs/Remote/Chat/LastChatDTO.swift
<br />
- ChattingList LastChat 항상 사진으로 나오는 오류 수정
<br />
<br /><br />
<br />
<br />
=> Fix: ChattingList LastChat 항상 사진으로 나오는 오류 수정

DogWalk.xcodeproj/project.pbxproj, DogWalk/Application/DogWalkApp.swift, DogWalk/Data/CoreData/CoreChatMessageTransformer.swift, DogWalk/Data/CoreData/CoreDataModel.xcdatamodeld/CoreDataModel.xcdatamodel/contents, DogWalk/Data/CoreData/Repository/ChatRepository.swift, DogWalk/Domain/UseCases/Chatting/ChattingRoomUseCase.swift, DogWalk/Domain/UseCases/HomeUseCase.swift, DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomView.swift, DogWalk/Presentatiton/Screens/Home/HomeIntent.swift, DogWalk/Presentatiton/Screens/Home/HomeView.swift
<br />
- 채팅방 이전 사진 로드 불가 오류 수정
- 홈뷰 인기 산책 인증 정렬 순서 오류 수정
<br />
<br /><br />
closed #166 
<br />
<br />
=> Fix:  채팅방 이전 사진 로드 불가 오류 수정

DogWalk.xcodeproj/project.pbxproj, DogWalk/Presentatiton/Screens/Home/HomeView.swift, DogWalk/Presentatiton/Screens/Map/WalkResult/WalkResultView.swift
<br />
- HomeView 이미지 뒤로 배치
- WalkResult 이미지 변경
<br />
<br /><br />
closed #148
<br />
=> Chore: Modifying Images

DogWalk.xcodeproj/project.pbxproj, DogWalk/Data/Repositories/Local/Image/ImageCacheManager.swift, DogWalk/Presentatiton/Components/Common/CommonImageView.swift, DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomView.swift, DogWalk/Presentatiton/Screens/Community/Detail/CommunityDetailView.swift
<br />
- 이미지 캐싱 Etag 제거
- 이미지 캐싱 document에 저장되는 경우 로직 구현 (ex: 채팅방 이미지)
<br />
<br /><br />
<br />
<br />
=> Refactor: 이미지 캐싱

DogWalk.xcodeproj/project.pbxproj, DogWalk/Presentatiton/Screens/Map/LocationManager.swift, DogWalk/Presentatiton/Screens/Map/MapOverview/MapView.swift
<br />
- 권한 허용 안할시 현재위치 버튼 눌렀을 때 예외처리
- 가만히 있을 때 경로 처리
<br />
<br /><br />
closed #170
<br />
=> Refactor:exception and path handling in map view

README.md
<br />
<br />
<br /><br />
<br />
<br />
=> Feat: Create README.md
